### ISSUE TITLE
Discrepancy in used date-time format

### ISSUE THREAD

**Issue by Fxr12042** [cisagov/CSAF#29]
# 🐛 Summary #

Commit f0feea7b7ff95ce932b9859aeed426fa1c43424e contains entries in ROLIE document which use different date-time format for published and updated fields; the miliseconds are omitted

## To reproduce ##

Open ROLIE document and confirm the published and updated fields for ICSA-24-011-11, ICSA-24-011-10, ICSA-24-011-09, ICSA-24-011-08, ICSA-24-011-07 and ICSA-24-011-06 uses a different date-time format than other entries

## Expected behavior ##

Entries in the ROLIE document use the same date-time format for every entry

## Any helpful log output or screenshots ##

n/a

**Comment by mstrad** [comment]
Hello @Fxr12042. Thank you for bringing this item to our attention!

According to the [Oasis-Open CSAF Standard](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html) all dates and times should be stored in the **date-time** format. For reference of the **date-time** format, Oasis-Open provides a summary and example in their document [Extended DateTime Format for the Browser Binding](https://www.oasis-open.org/committees/download.php/53091). 

Since both variations of the **date-time** format (with milliseconds and without milliseconds) are acceptable within the Oasis-Open CSAF Standard, CISA does not consider this an issue at the present time.

Thank you.
